# Configuración del límite de peticiones (Anti-DoS)
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    listen 80;

    # Mitigación de conexiones lentas (Slowloris)
    client_body_timeout   10s;
    client_header_timeout 10s;
    keepalive_timeout     15s;
    send_timeout          10s;

    # 1. Todo lo que vaya a /api lo maneja el contenedor backend
    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;
        limit_req_status 429;

        # Nota: Usamos 'http://backend:3001' porque Docker resuelve los nombres de 
        # servicios de docker-compose como si fueran dominios internos.
        proxy_pass http://backend:3001; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }

    # 2. El resto de peticiones (/) van hacia el contenedor frontend (React/Vite)
    location / {
        proxy_pass http://frontend:5173; # Ajusta el puerto al que use tu Dockerfile de frontend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}